# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upstream_id', models.CharField(help_text='The ID used by the vendor to refer to this advisory', max_length=200, verbose_name='Upstream ID')),
                ('short_description', models.CharField(help_text='One-line description of the advisory', max_length=200, null=True)),
                ('description', models.TextField(help_text='Longer description of the advisory', null=True)),
                ('action', models.TextField(help_text='What, if any, actions need to be taken to address the advisory', null=True)),
                ('issued', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which the advisory was issued')),
                ('source', models.CharField(choices=[('ubuntu', 'Ubuntu'), ('debian', 'Debian')], help_text='Vendor source of the advisory', max_length=32)),
                ('severity', models.IntegerField(blank=True, choices=[(0, 'Undecided'), (1, 'Low'), (2, 'Standard'), (3, 'High'), (4, 'Critical')], default=0, help_text='Local severity of the advisory, once it has been reviewed')),
                ('search_keywords', models.TextField(blank=True, help_text='Space separated list of keywords used to speed up search', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Person who locally reviewed the advisory for its overall severity (or None if the severity was determined automatically)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'advisories',
                'ordering': ['-issued'],
            },
        ),
        migrations.CreateModel(
            name='BinaryPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='Name of binary package', max_length=200)),
                ('release', models.CharField(choices=[('squeeze', 'Debian Squeeze 6.0'), ('wheezy', 'Debian Wheezy 7.0'), ('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04')], help_text='Specific release to which this package belongs', max_length=32)),
                ('safe_version', models.CharField(help_text="Package version that is to be considered 'safe' at the issue of this advisory", max_length=200, null=True)),
                ('architecture', models.CharField(help_text='Machine architecture', max_length=200, null=True)),
                ('advisory', models.ForeignKey(help_text='Advisory to which this package belongs', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
            ],
            options={
                'verbose_name_plural': 'binary packages',
                'ordering': ['-package'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_package_name', models.CharField(help_text='Name of binary package causing the problem', max_length=200, verbose_name='Package name')),
                ('installed_package_version', models.CharField(help_text='Version of binary package causing the problem', max_length=200, verbose_name='Version')),
                ('installed_package_architecture', models.CharField(help_text='Architecture of binary package causing the problem', max_length=200, verbose_name='Architecture')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Discovered')),
                ('fixed', models.DateTimeField(null=True)),
                ('fixed_by', models.CharField(choices=[('removed', 'Package removed')], help_text='Way in which the problem was resolved', max_length=200, null=True)),
                ('advisory', models.ForeignKey(help_text='Advisory that has caused this problem', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
                ('host', models.ForeignKey(help_text='Host which has the problem', on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
                ('safe_package', models.ForeignKey(help_text='The safe package version provided by the advisory', on_delete=django.db.models.deletion.CASCADE, to='advisories.BinaryPackage')),
            ],
        ),
        migrations.CreateModel(
            name='SourcePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(help_text='Name of source package', max_length=200)),
                ('release', models.CharField(choices=[('squeeze', 'Debian Squeeze 6.0'), ('wheezy', 'Debian Wheezy 7.0'), ('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04')], help_text='Specific release to which this package belongs', max_length=32)),
                ('safe_version', models.CharField(help_text="Package version that is to be considered 'safe' at the issue of this advisory", max_length=200)),
                ('advisory', models.ForeignKey(help_text='Advisory to which this package belongs', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
            ],
            options={
                'verbose_name_plural': 'source packages',
                'ordering': ['-package'],
            },
        ),
        migrations.AddField(
            model_name='binarypackage',
            name='source_package',
            field=models.ForeignKey(blank=True, help_text='If set, the source package from which this binary package was generated', null=True, on_delete=django.db.models.deletion.CASCADE, to='advisories.SourcePackage'),
        ),
    ]
