# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('advisories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedHosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_resolved', models.BooleanField(default=True, help_text='If all the problems from the advisory have been resolved')),
                ('advisory', models.ForeignKey(help_text='Advisory that affects the host', on_delete=django.db.models.deletion.CASCADE, to='advisories.Advisory')),
                ('host', models.ForeignKey(help_text='The affected host', on_delete=django.db.models.deletion.CASCADE, to='hosts.Host')),
            ],
        ),
        migrations.AlterField(
            model_name='binarypackage',
            name='release',
            field=models.CharField(choices=[('squeeze', 'Debian Squeeze 6.0'), ('wheezy', 'Debian Wheezy 7.0'), ('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04'), ('xenial', 'Ubuntu Xenial LTS 16.04')], help_text='Specific release to which this package belongs', max_length=32),
        ),
        migrations.AlterField(
            model_name='sourcepackage',
            name='release',
            field=models.CharField(choices=[('squeeze', 'Debian Squeeze 6.0'), ('wheezy', 'Debian Wheezy 7.0'), ('jessie', 'Debian Jessie 8.0'), ('precise', 'Ubuntu Precise LTS 12.04'), ('trusty', 'Ubuntu Trusty LTS 14.04'), ('xenial', 'Ubuntu Xenial LTS 16.04')], help_text='Specific release to which this package belongs', max_length=32),
        ),
    ]
