# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0002_auto_20170804_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AffectedHosts',
            new_name='AffectedHost',
        ),
    ]
