# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0003_auto_20170804_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectedhost',
            name='advisory',
        ),
        migrations.RemoveField(
            model_name='affectedhost',
            name='host',
        ),
        migrations.DeleteModel(
            name='AffectedHost',
        ),
    ]
