# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('advisories', '0004_auto_20170808_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='affected_hosts',
            field=models.ManyToManyField(through='advisories.Problem', to='hosts.Host'),
        ),
    ]
