# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisories', '0005_advisory_affected_hosts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name_plural': 'problems'},
        ),
        migrations.AlterField(
            model_name='advisory',
            name='affected_hosts',
            field=models.ManyToManyField(help_text='All hosts that have a problem with this advisory', through='advisories.Problem', to='hosts.Host'),
        ),
    ]
