# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-14 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hash_of_host',
            field=models.CharField(help_text='The has of all the fields of the object, used for detecting changes.', max_length=64, null=True),
        ),
    ]
